"""create_suppliers_table

Revision ID: 015d7bf93d56
Revises: 48f960aa6c1d
Create Date: 2026-01-06 08:40:04.263945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015d7bf93d56'
down_revision = '48f960aa6c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_title', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('fax', sa.String(length=30), nullable=True),
    sa.Column('homepage', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_index(op.f('ix_suppliers_city'), 'suppliers', ['city'], unique=False)
    op.create_index(op.f('ix_suppliers_company_name'), 'suppliers', ['company_name'], unique=False)
    op.create_index(op.f('ix_suppliers_country'), 'suppliers', ['country'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppliers_country'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_company_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_city'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
