"""create_categories_table

Revision ID: 48f960aa6c1d
Revises: 10951d0a87f6
Create Date: 2026-01-06 07:04:42.222218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f960aa6c1d'
down_revision = '10951d0a87f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
