"""Add deleted_at to Category

Revision ID: 868b9cf190cb
Revises: e0e020525a04
Create Date: 2026-01-06 17:25:47.011167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868b9cf190cb'
down_revision = 'e0e020525a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'deleted_at')
    # ### end Alembic commands ###
