"""create_employees_table

Revision ID: b16a30648cb5
Revises: a994d03e7142
Create Date: 2026-01-06 13:20:42.327183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16a30648cb5'
down_revision = 'a994d03e7142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('employee_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('title_of_courtesy', sa.String(length=25), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('hire_date', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(length=60), nullable=True),
    sa.Column('city', sa.String(length=15), nullable=True),
    sa.Column('region', sa.String(length=15), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=15), nullable=True),
    sa.Column('home_phone', sa.String(length=24), nullable=True),
    sa.Column('extension', sa.String(length=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reports_to', sa.Integer(), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reports_to'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_index(op.f('ix_employees_city'), 'employees', ['city'], unique=False)
    op.create_index(op.f('ix_employees_country'), 'employees', ['country'], unique=False)
    op.create_index(op.f('ix_employees_last_name'), 'employees', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_last_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_country'), table_name='employees')
    op.drop_index(op.f('ix_employees_city'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
